builders:
  isar_entity:
    import: "package:isar_entity_generator/builder.dart"
    builder_factories: ["isarToEntity"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: cache
