name: isar_entity_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  recase: ^4.1.0
  analyzer: ^5.0.0
  build: ^2.1.2

dev_dependencies:
  build_runner: ^2.1.5
  source_gen: ^1.1.1
  lints: ^2.0.0
  test: ^1.16.0
